export enum ROUTE_NAME {
  BOTTOM_TAB = 'BOTTOM_TAB',
  HOME_SCREEN = 'HOME_SCREEN',
  PROFILE_SCREEN = 'PROFILE_SCREEN',
  SETTING_SCREEN = 'SETTING_SCREEN',
  MODAL_SCREEN = 'MODAL_SCREEN',
  HOME_STACK = 'HOME_STACK',
  PROFILE_STACK = 'PROFILE_STACK',
}
